In [1]:
from bs4 import BeautifulSoup
import requests
from requests import get
import pandas as pd
import numpy as np
import re
import dateutil.parser

In [2]:
response = requests.get('https://www.the-numbers.com/box-office-star-records/domestic/lifetime-acting/top-grossing-leading-stars')
response.status_code

200

In [3]:
soup = BeautifulSoup(response.text, 'lxml')

In [4]:
actors_list = []
top_100_actors = soup.find_all(id="page_filling_chart")[1].find_all("a")
for text in top_100_actors:
    print(text.text)
    actors_list.append(text.text)

Samuel L. Jackson
Robert Downey, Jr.
Tom Hanks
Scarlett Johansson
Bradley Cooper
Harrison Ford
Chris Evans
Chris Hemsworth
Zoe Saldana
Chris Pratt
Tom Cruise
Johnny Depp
Eddie Murphy
Will Smith
Mark Ruffalo
Don Cheadle
Vin Diesel
Matt Damon
Jeremy Renner
Dwayne Johnson
Emma Watson
Adam Sandler
Chadwick Boseman
Bruce Willis
Ben Stiller
Nicolas Cage
Karen Gillan
Steve Carell
Jim Carrey
Leonardo DiCaprio
Josh Brolin
Jennifer Lawrence
Robin Williams
Liam Neeson
Benedict Cumberbatch
Robert De Niro
Tom Holland
Daniel Radcliffe
Hugh Jackman
Sandra Bullock
Brad Pitt
Gwyneth Paltrow
Cameron Diaz
Denzel Washington
Ian McKellen
Elizabeth Olsen
Sebastian Stan
Dave Bautista
Tom Hiddleston
Rupert Grint
Ben Affleck
Paul Bettany
Julia Roberts
Ewan McGregor
Mel Gibson
Kevin Hart
John Travolta
Mark Hamill
Danai Gurira
Letitia Wright
Mark Wahlberg
Will Ferrell
Owen Wilson
Adam Driver
Morgan Freeman
Daisy Ridley
Tim Allen
John Boyega
Christian Bale
Natalie Portman
Sylvester Stallone
George Clooney
Mike Myers
Meryl Streep
Jack Black
Ryan Reynolds
Keanu Reeves
Pom Klementieff
Shia LaBeouf
Josh Gad
Paul Rudd
Channing Tatum
Kevin Costner
Idris Elba
Clint Eastwood
Seth Rogen
Michael Douglas
Benedict Wong
Lupita Nyong'o
Arnold Schwarzenegger
Dustin Hoffman
Carrie Fisher
Kristen Stewart
Orlando Bloom
Anthony Hopkins
Michelle Pfeiffer
Martin Freeman
Chris Pine
Steve Martin
Nicole Kidman
1-100
101-200
201-300
301-400
401-500
501-1,000 »

In [5]:
top_actors_list = pd.DataFrame(actors_list)
top_actors_list.drop(top_actors_list.tail(6).index, inplace=True)
top_actors_list.rename(columns={0:"actors"}, inplace=True)

#### table = soup.find_all(id="page_filling_chart")[1]

top_100_actors = []

for row in soup.find_all(id="page_filling_chart")[1]:
    for link in row.find_all('a'):
        print(str(link.text))

In [6]:
top_actors_list

                actors
0    Samuel L. Jackson
1   Robert Downey, Jr.
2            Tom Hanks
3   Scarlett Johansson
4       Bradley Cooper
..                 ...
95   Michelle Pfeiffer
96      Martin Freeman
97          Chris Pine
98        Steve Martin
99       Nicole Kidman

[100 rows x 1 columns]

In [14]:
top_actors_list.to_pickle("actorslist.pkl")

In [7]:
response = requests.get('https://www.the-numbers.com/box-office-star-records/domestic/lifetime-specific-technical-role/director')
response.status_code

200

In [8]:
soup = BeautifulSoup(response.text, 'lxml')

In [9]:
directors_list = []
top_100_directors = soup.find_all(id="page_filling_chart")[1].find_all("a")
for text in top_100_directors:
    print(text.text)
    directors_list.append(text.text)

Steven Spielberg
Michael Bay
Anthony Russo
Joe Russo
J.J. Abrams
Peter Jackson
Ron Howard
Robert Zemeckis
Christopher Nolan
Clint Eastwood
James Cameron
Tim Burton
Jon Favreau
David Yates
Chris Columbus
George Lucas
Ridley Scott
Gore Verbinski
Sam Raimi
Francis Lawrence
Brad Bird
Todd Phillips
Chris Renaud
Bryan Singer
Roland Emmerich
M. Night Shyamalan
Zack Snyder
Bill Condon
Pierre Coffin
Andrew Stanton
Andrew Adamson
Brett Ratner
Shawn Levy
Jay Roach
James Wan
Joss Whedon
Ivan Reitman
Dennis Dugan
Tony Scott
Richard Donner
Barry Sonnenfeld
Steven Soderbergh
Jon Turteltaub
John Lasseter
Conrad Vernon
Martin Scorsese
Garry Marshall
Tyler Perry
Sam Mendes
Joel Schumacher
Pete Docter
Jake Kasdan
Tom McGrath
Guy Ritchie
James Mangold
Tom Shadyac
Carlos Saldanha
Chris Buck
Jennifer Lee
Rob Minkoff
Tim Story
Joe Johnston
David Fincher
Rian Johnson
Justin Lin
Peter Segal
F. Gary Gray
Ryan Coogler
Sydney Pollack
Barry Levinson
Robert Rodriguez
Quentin Tarantino
Bobby Farrelly
Raja Gosnell
Rob Marshall
Mike Nichols
Wolfgang Petersen
Oliver Stone
Eric Darnell
Peter Farrelly
Paul Greengrass
Adam Shankman
Ron Clements
James Gunn
Gareth Edwards
Rich Moore
Gary Ross
Antoine Fuqua
Jon Watts
John Musker
Andy Wachowski
Peter Berg
Phil Lord
Christopher Miller
Martin Campbell
Stephen Sommers
Peyton Reed
Adam McKay
Mike Mitchell
Francis Ford Coppola
1-100
101-200
201-300
301-400
401-500
501-1,000 »

In [10]:
top_directors_list = pd.DataFrame(directors_list)
top_directors_list.drop(top_directors_list.tail(6).index, inplace=True)
top_directors_list.rename(columns={0:"directors"}, inplace=True)

In [11]:
top_directors_list

               directors
0       Steven Spielberg
1            Michael Bay
2          Anthony Russo
3              Joe Russo
4            J.J. Abrams
..                   ...
95       Stephen Sommers
96           Peyton Reed
97            Adam McKay
98         Mike Mitchell
99  Francis Ford Coppola

[100 rows x 1 columns]

In [15]:
top_directors_list.to_pickle("directorslist.pkl")